### ISSUE TITLE
Do not enforce EEPROM regulatory restrictions

### ISSUE THREAD

**Issue by vladns** [CodePhase/patch-atheros-regdom#3]
What should be the answer to the question "Do not enforce EEPROM regulatory restrictions" yes or no? The question does not sound unambiguous, because. I am using google translator.

**Comment by CodePhase** [comment]
To remove the EEPROM restrictions, choose yes.  This is the default.  To keep the EEPROM restrictions and have the ath10k driver behave the same as no modification, choose no.
