### ISSUE TITLE
Debian support

### ISSUE THREAD

**Issue by CristianVladescu** [CodePhase/patch-atheros-regdom#4]
Any idea how the same can be accomplished for Debian?

I followed [this](https://medium.com/@renaudcerrato/how-to-build-your-own-wireless-router-from-scratch-part-3-d54eecce157f) Ubuntu tutorial on 18.04, and it worked, it took 35 minutes.
But when I try the same on Debian 11, `fakeroot debian/rules binary-generic` fails because `make: *** No rule to make target 'binary-generic'`, and if I use `binary` instead of `binary-generic`, it compiles, but it takes much longer and I'm not sure is the same thing anyway.

Now I was looking at `athpatch.sh`, but these
```
  cp /usr/lib/modules/${KVERSION}.${ARCH}/build/Module.symvers ./
  cp ~/rpmbuild/SOURCES/kernel-${ARCH}.config ./.config
```
don't apply for Debian, and I have no clue what the equivalent is.

**Comment by CristianVladescu** [comment]
Ok, I figured it out. I can call make with the `M` variable set so it compiles only the ath module:
`make -j8 M=$(pwd)/drivers/net/wireless/ath modules`  
I have documented all the steps required to patch the driver in Debian [here](https://github.com/CristianVladescu/deb-ath-user-regd).

**Comment by CodePhase** [comment]
This is great, thank you for following up!  I was just coming in to address it and you beat me to it.  Do you want to submit a PR for the additional information?

**Comment by CristianVladescu** [comment]
I'm getting different results across different Debian distros. It worked in vanilla Debian, but now I'm struggling to make it work in Proxmox (which is also based on Debian but it's using kernel 5.19). I think there are too many unknown variables to make a fit-all script, for now.
